### ISSUE TITLE
Breakdown Dropdown Bug

### ISSUE THREAD

**Issue by Tragedy-dev** [earthernsence/baba-make-cash-dev#2]
When I hover over the text the dropdown shows but only displays the numbers as X.
![Screenshot 2020-04-09 at 13 18 42](https://user-images.githubusercontent.com/54042397/78927584-c04fe080-7a64-11ea-8114-bd0d930c842e.png)

(Sorry if this is not the place to submit bugs or if it's not a bug)

**Comment by earthernsence** [comment]
yes, this is the appropriate place to put bugs

I currently have not put anything in the JS to change those yet as I've been more focused on getting the CSS to cooperate with me for other things.

this WILL be in the next update on this dev repo (not stable 3, but stable 4), and stable 4 will come with a lot of new things as well that I have to make work with the breakdown.

eventually the breakdown could end up in stats, because the tooltip will probably end up having to overflow and it makes more sense in stats.

i apologize for the inconvenience
